# Generated by Django 4.1.5 on 2023-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.TextField(max_length=50)),
                ('ticket', models.TextField(max_length=50)),
                ('signature', models.CharField(default='Loud musiq no silence', max_length=200)),
            ],
        ),
    ]
